### ISSUE TITLE
Iniciar sesión - agregar "required" a los input

### ISSUE THREAD

**Issue by KatuGT** [lucianobonilla27/InventoryIQ-Front#5]
si los campos son requeridos debería no dejarme mandar nada al back directamente, actualmente si lo permite y me devuelve este error
![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/72964e2f-28c0-4776-8a6d-6d6470027936)

**Comment by facumedina** [comment]
Se agregó el required a los input del login.

**Comment by KatuGT** [comment]
> Se agregó el required a los input del login.

Facu, me parece que no deployaron este cambio por que no tienen todavie y el formulario sigue mandandose vacio
![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/d0e62c71-bef8-4a5a-b3db-31a396894cba)

**Comment by KatuGT** [comment]
![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/8a2cba7d-a512-4450-9bac-cedc9b52eb5c)
Listo, corregido

**Comment by KatuGT** [comment]
Probado y aprobado!
