### ISSUE TITLE
Registro - Indicar cuales son los carácteres especiales admitidos en el modal del error

### ISSUE THREAD

**Issue by KatuGT** [lucianobonilla27/InventoryIQ-Front#6]
Por ejemplo intento crear una contraseña que incluye "}" y no lo permite

**Comment by facumedina** [comment]
Se realizó la corrección de los caracteres especiales.

**Comment by KatuGT** [comment]
> Se realizó la corrección de los caracteres especiales.

![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/ed473449-cc7f-4b29-86d0-8af35553f024)
todavía no se observa el cambio

**Comment by KatuGT** [comment]
![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/69cd8458-e35d-46a4-8b95-06946c8923f2)
Listo. corregido
