### ISSUE TITLE
Registro - error al registrar pero muestra el modal de "success"

### ISSUE THREAD

**Issue by KatuGT** [lucianobonilla27/InventoryIQ-Front#7]
Me intento registrar con el mismo email con el que ya me registre y el backed devuelve

{"message":"Error al registrar el usuario"}

deben esperar la respuesta exitosa (o no) del backed y recién mostrar el modal según corresponda

![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/2aebb4ac-c772-48d4-9c39-1ad5659ed36e)

**Comment by lucianobonilla27** [comment]
corregido

**Comment by KatuGT** [comment]
![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/69ee075b-784a-43d9-9bc5-797535bf08f4)
Porfa, indiquen de manera clara cual es el error, el usuario debe saber que ese email ya esta registrado si ese es el error 

> corregido

**Comment by KatuGT** [comment]
![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/845a8ff7-ce49-4dc9-a007-90e3f5ef3e35)
corregido
