### ISSUE TITLE
Creación producto - modal se lanza sin esperar respuesta del back

### ISSUE THREAD

**Issue by KatuGT** [lucianobonilla27/InventoryIQ-Front#8]
Al igual que con lo de registro, en su codigo no veo que esperen que la respuesta sea exitosa para mostrar el modal, 
no  pude forzar un error ya que los productos no tienen otra validación mas que los campos sean tipo "string"

pero no deberían mostrar el modal de Producto creado sin saber si se creo correctamente
![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/5286edba-8ba5-4f3d-89f6-dbe9c55a7a48)

**Comment by lucianobonilla27** [comment]
corregido

**Comment by KatuGT** [comment]
![image](https://github.com/lucianobonilla27/InventoryIQ-Front/assets/38865485/9c985e23-a6e9-41b1-8c8a-09128bde65a4)

Bien, mejor, solo que ahora me sale el error {"message":"La cantidad debe ser un número entero positivo"}, deberian hacer que el campo cantidad se mande como "number" (por default manda string) o  si no en el back cambiar el "type" para que acepte un strinig, cualquiera de esas dos soluciones es valida
> corregido

**Comment by KatuGT** [comment]
corregido
